---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: todos
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: todos
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: asia-northeast1-docker.pkg.dev/sonic-arcadia-437913-c5/todos/frontend:latest
        ports:
        - containerPort: 3000
          name: http
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #   limits:
        #     cpu: "100m"
        #     memory: "128Mi"
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: todos
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
      tier: backend
  template:
    metadata:
      labels:
        app: todos
        tier: backend
    spec:
      containers:
      - name: backend
        image: asia-northeast1-docker.pkg.dev/sonic-arcadia-437913-c5/todos/backend:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        #resources:
        #  requests:
        #    cpu: "200m"
        #    memory: "256Mi"
        #  limits:
        #    cpu: "200m"
        #    memory: "256Mi"
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3001
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3001
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   readOnlyRootFilesystem: true