---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: todos
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: todos
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: asia-northeast1-docker.pkg.dev/sonic-arcadia-437913-c5/todos/frontend:v4.0.1
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "200m"
            memory: "900Mi"
          limits:
            cpu: "200m"
            memory: "900Mi"
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: todos
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
      tier: backend
  template:
    metadata:
      labels:
        app: todos
        tier: backend
    spec:
      containers:
      - name: backend
        image: asia-northeast1-docker.pkg.dev/sonic-arcadia-437913-c5/todos/backend:v4.0.1
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: uri
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
