---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sa
automountServiceAccountToken: true
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
    gcpsm:
      projectID: sonic-arcadia-437913-c5
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1-a
          clusterName: test
          serviceAccountRef:
            name: readonly-sa
            namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: mongodb-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: username
  - secretKey: password
    remoteRef:
      key: password
  - secretKey: uri
    remoteRef:
      key: uri
