---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sa
  annotations:
    iam.gke.io/gcp-service-account: "readonly-sa@sonic-arcadia-437913-c5.iam.gserviceaccount.com"
automountServiceAccountToken: true

