#namespace for secrets

apiVersion: v1
kind: Namespace
metadata:
  name: readonly-ns

---
#creating service accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-ns
  namespace: readonly-ns
automountServiceAccountToken: true
---
