name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE_NAME: frontend
      BACKEND_IMAGE_NAME: backend
      PROJECT_ID: sonic-arcadia-437913-c5
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: google-github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: |
            docker build -t $FRONTEND_IMAGE_NAME:latest . -f ./todos_app/frontend/
            docker build -t $BACKEND_IMAGE_NAME:latest . -f ./todos_app/backend/

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/version_update.sh -v major

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $FRONTEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_FRONTEND_IMAGE_NAME:latest
        docker tag $FRONTEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:$GIT_TAG
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:latest
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:$GIT_TAG
        docker tag $BACKEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:latest
        docker tag $BACKEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:$GIT_TAG
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:latest
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:$GIT_TAG