name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ] 
    #paths: ['todos_app/**']

permissions:
  contents: 'write'
  id-token: 'write'
  pull-requests: write

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      FRONTEND_IMAGE_NAME: frontend
      BACKEND_IMAGE_NAME: backend
      PROJECT_ID: sonic-arcadia-437913-c5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/354499143468/locations/global/workloadIdentityPools/github/providers/github'
        service_account: 'github@sonic-arcadia-437913-c5.iam.gserviceaccount.com'
        project_id: 'sonic-arcadia-437913-c5'
        token_format: 'access_token'
        create_credentials_file: true

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Build Docker Image
      run: |
            cd ./todos_app/frontend/ && docker build -t $FRONTEND_IMAGE_NAME:latest . && cd ../../
            cd ./todos_app/backend/ && docker build -t $BACKEND_IMAGE_NAME:latest . && cd ../../

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./scripts/version_update.sh -v patch

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $FRONTEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:latest
        docker tag $FRONTEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:$GIT_TAG
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:latest
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$FRONTEND_IMAGE_NAME:$GIT_TAG
        docker tag $BACKEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:latest
        docker tag $BACKEND_IMAGE_NAME:latest asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:$GIT_TAG
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:latest
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/todos/$BACKEND_IMAGE_NAME:$GIT_TAG

    - name: Update_version
      id: update_version
      run: |
          sed -i -E "s/(CURRENT_VERSION=')[^']*(')/\1${{ steps.increment-git-tag.outputs.git-tag }}\2/" "./scripts/version_update.sh"
          sed -i "s/image: asia-northeast1-docker.pkg.dev\/sonic-arcadia-437913-c5\/todos\/\(backend\|frontend\):v[0-9]*\.[0-9]*\.[0-9]*/image: asia-northeast1-docker.pkg.dev\/sonic-arcadia-437913-c5\/todos\/\1:${{ steps.increment-git-tag.outputs.git-tag }}/" "./manifests/deployments.yaml"
          git tag ${{ steps.increment-git-tag.outputs.git-tag }}
          git push origin ${{ steps.increment-git-tag.outputs.git-tag }}
    - uses: stefanzweifel/git-auto-commit-action@v5